package pl.pjatk.jaz_26974_nbp.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
public class Request {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(name = "id", description = "ID of request - autogenerated", example = "1",
            accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;
    @Schema(name = "currency", description = "Currency code", example = "USD")
    private String currency;
    @Schema(name = "startDate", description = "Beginning date for calculations", example = "2025-06-16")
    private LocalDate startDate;
    @Schema(name = "endDate", description = "End date for calculations", example = "2025-06-21")
    private LocalDate endDate;
    @Schema(name = "rate", description = "Calculated rate", example = "3.45")
    private BigDecimal rate;
    @Schema(name = "requestDate", description = "Date and time when the request was made", example = "2025-06-21 15:50")
    private LocalDateTime requestDate;

    public Request() {
    }

    public Request(String currency, LocalDate startDate, LocalDate endDate, BigDecimal rate, LocalDateTime requestDate) {
        this.currency = currency;
        this.startDate = startDate;
        this.endDate = endDate;
        this.rate = rate;
        this.requestDate = requestDate;
    }

    //region Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public BigDecimal getRate() {
        return rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public LocalDateTime getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(LocalDateTime requestDate) {
        this.requestDate = requestDate;
    }
    //endregion
}
